### ISSUE TITLE
Mapping from original Anora tags to UPOS tags?

### ISSUE THREAD

**Issue by johann-petrak** [UniversalDependencies/UD_Spanish-AnCora#1]
The description of this corpus mentions that POS tags have been converted automatically from the original ANCORA tags to UPOS tags, but I was unable to find the appropriate code or mapping file.
Is this available somewhere?

**Comment by dan-zeman** [comment]
Originally, UD AnCora was converted from the CoNLL 2009 shared task dependency dataset through [HamleDT](https://ufal.mff.cuni.cz/hamledt), so the "original" tags were not as original as they could be.

The corpus now contains the EAGLES tags from the AnCora XML files (pre-CoNLL 2009), which could help with the mapping.
