### ISSUE TITLE
Can this dataset be used commercially through another third party library?

### ISSUE THREAD

**Issue by samarth12** [UniversalDependencies/UD_Spanish-AnCora#3]
Hi, 

I am interested in using some language models built using this particular dataset in Spanish. These language models were trained by [Spacy](https://spacy.io) and [Stanza](https://stanfordnlp.github.io/stanza/).

[Here](https://spacy.io/models/es) is the link to the model made available by Spacy. Spacy itself as a library is available to use commercially `MIT`, which means I can use their Spanish language model but the dataset it uses is `GPL`. 

[Here](https://stanfordnlp.github.io/stanza/available_models.html) is the link to the model made available by Stanza (scroll down to Spanish). Stanza is available for commercial use through `Apache 2.0` as well. 

I am interested to know if the Spanish AnCora is available through a commercial license? Or if the dataset can be used commercially if it used to train language models by another company/library that offers its services commercially. 

I would appreciate any help or direction, thank you!

**Comment by dan-zeman** [comment]
Any licensing questions have to be directed to the providers of the original pre-UD dataset at the University of Barcelona. I'm afraid that they may not be monitoring this issue tracker. The website of the AnCora corpus is [here](http://clic.ub.edu/corpus/).
