### ISSUE TITLE
Bug in dev file

### ISSUE THREAD

**Issue by vmtenorio** [UniversalDependencies/UD_Spanish-AnCora#5]
I wanted to report a bug in the es_ancora-ud-dev.conllu. Please correct me if I'm mistaken, but I think that in line 19600 of the file, the id of the multiword "quitárselas" appears to cover words from 33 to 34, but in fact, it should be covering 33-35.

33-34	quitárselas	_	_	_	_	_	_	_	SpaceAfter=No
33	quitar	quitar	VERB	VERB	VerbForm=Inf	14	xcomp	_	_
34	se	él	PRON	PRON	Case=Dat|Person=3|PrepCase=Npr|PronType=Prs	33	iobj	_	_
35	las	él	PRON	PRON	Case=Acc|Gender=Fem|Number=Plur|Person=3|PrepCase=Npr|PronType=Prs	33	iobj	_	SpaceAfter=No

**Comment by dan-zeman** [comment]
Thanks for reporting! This bug is already fixed in the dev branch, together with several other similar instances that were discovered recently. The fix will propagate to the next UD release in May.
