### ISSUE TITLE
Annotation of CESS-CAST-A-20000817-11033-s12

### ISSUE THREAD

**Issue by nikitakit** [UniversalDependencies/UD_Spanish-AnCora#8]
Would someone be willing to clarify for me whether `CESS-CAST-A-20000817-11033-s12` is annotated correctly?

> En la Universidad "no estaba seguro de lo que Al iba a acabar haciendo con su vida, pero siempre supe que tenía el cerebro y el corazón para cambiar el mundo entero", aseguró el actor.

_(in this sentence "Al" refers to Al Gore)_

<img width="390" alt="CESS-CAST-A-20000817-11033-s12" src="https://github.com/UniversalDependencies/UD_Spanish-AnCora/assets/252225/6aedcbdb-6943-40ed-ae0c-f2119f4dc067">

The portion "de lo que Al iba a acabar haciendo con su vida" has a highly non-projective structure, and I don't understand why none of "de"/"lo"/"que" share the same head, why "con so vida" goes with "acabar" rather than "haciendo", and why "haciendo" attaches to "iba" instead of "acabar".

**Comment by dan-zeman** [comment]
Thanks for reporting! This was indeed messed up, probably lost in conversion. Nevertheless, the correct annotation will still be non-projective, as _que_ is the object of _haciendo_. Fixed now in dev.
